class MyException extends Exception {
    private String Teks;
    MyException(String s) {
        Teks = "Exception generated by: " + s;
    }
    @Override
    public String toString() {
        return Teks;
    }
}
public class Percobaan12 {
    static void tampil(String s) throws MyException {
        System.out.println("Tampil");
        if (s.equals("amir")) {
            throw new MyException(s);
        }
        System.out.println("OK!");
    }
    public static void main(String args[]) {
        try {
            tampil("ali");
            tampil("amir");
        } catch (MyException ex) {
            System.out.println("Tangkap: " + ex);
        }
    }
}
